# Generated by Django 5.1.3 on 2024-11-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_image",
            field=models.ImageField(upload_to="media/project_images"),
        ),
    ]
