# Generated by Django 5.1.3 on 2024-11-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP", "0002_alter_project_project_image"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="project",
            name="unique_project_per_user",
        ),
        migrations.RemoveField(
            model_name="project",
            name="created_by",
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("project_name",), name="unique_project"
            ),
        ),
    ]
